version: '3.8'

services:
  admin:
    build:
      context: ./preregistration_project
      # 소스 폴더(preregistration_project) 기준 상위(..)의 docker 폴더 참조
      dockerfile: ../docker/admin.Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8001:80"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ../Backend
      # 소스 폴더(Backend) 기준 상위(..)의 docker 폴더 참조
      dockerfile: ../docker/backend.Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ../front
      # 소스 폴더(front) 기준 상위(..)의 docker 폴더 참조
      dockerfile: ../docker/frontend.Dockerfile
    networks:
      - app-network
    restart: unless-stopped

  frontend-balancer:
    build:
      context: ./nginx
      # 소스 폴더(nginx) 기준 상위(..)의 docker 폴더 참조
      dockerfile: ./nginx/nginx.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  app-network: