version: '3.8'

services:
  backend:
    build:
      context: ../Backend
      dockerfile: ../docker/backend.Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - reservation-network
    restart: unless-stopped

  frontend:
    build:
      context: ../front
      dockerfile: ../docker/frontend.Dockerfile
    networks:
      - reservation-network
    restart: unless-stopped

  frontend-balancer:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile 
    ports:
      - "8000:80"
    depends_on:
      - frontend
    networks:
      - reservation-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  reservation-network: